name: my_workflows

on:
  push:
    branches:
      - main
jobs:
  mytesting:
    runs-on: ubuntu-latest
    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
      
    - name: ls result
      run: ls -la
