name: my_workflows

on:
  push:
    branches:
      - 'main'
env:
  NAME: Jhon
  RUNNER_OS: WINDOWS
  
jobs:
  mytesting:
    runs-on: ubuntu-latest
    env:
      AGE: 18
      CONTINUE: true
      time: 3
    steps:
      - name: git clone our repo
        uses: actions/checkout@v1
      
      - name: ls result
        id: testid
        continue-on-error: true
        run: ls -la asdfqwefracACD

      - name: echo Name
        run: |
          echo "My name is $NAME"
          echo ${{ env.NAME }}
        
      - name: echo year
        run: |
          echo "I am $AGE years old"
          echo ${{ env.AGE }}
        
      - name: run file.sh
        run: bash file.sh
      
      - name: print by id
        run: echo ${{ toJson(steps.testid.outcom) }}
        
      - id: step1
        run: echo "test=world" >> $GITHUB_OUTPUT
        
      - name: print world
        run: echo ${{ steps.step1.outputs.test }}
        
      - name: condition1
        if: runner.os == 'windows'
        run: echo "The operation system on the runner is $env.RUNNER_OS."
        
      - name: condition2
        if: runner.os != "windows"
        run: echo "The operation system on the runner is not windows, its $RUNNER_OS."
      
