name: my_workflows

on:
  push:
    branches:
      - 'main'
      
env:
  DAY: Monday
jobs:
  mytesting:
    runs-on: ubuntu-latest
    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
      
    - name: ls result
      run: ls -la
    - name: "Say Hello Mona it's Monday"
      run: echo "Today is < $DAY"
    - name: echo hello
      run: |
        echo hello
      
