name: my_workflows

on:
  push:
    branches:
      - 'main'
env:
  NAME: Jhon
jobs:
  mytesting:
    runs-on: ubuntu-latest
    env:
      AGE: 18
    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
      
    - name: ls result
      id: testid
      continue-on-error: true
      run: ls -la asdfqwefracACD
      
    - name: echo Name
      run: |
        echo "My name is $NAME"
        echo ${{ env.NAME }}
        
    - name: echo year
      run: |
        echo "I am $AGE years old"
        echo ${{ env.AGE }}
        
    - name: run file.sh
      run: bash file.sh
      
    - name: print by id
      run: echo ${{ toJson(steps.testid.outcom) }}
      
    - name: matrix 
      id: set-matrix
      run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
      
    - name: verify
      run: echo ${{ fromJSON(steps.set-matrix.outputs) }}
      
      
